name: expenses_tracker_app
description: "An expenses tracker app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  floor: ^1.5.0
  sqflite: ^2.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  intl: ^0.18.1
  uuid: ^4.3.3
  fl_chart: ^0.68.0
  image_picker: ^1.0.7

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  go_router: ^14.0.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.0.0
  connectivity_plus: ^7.0.0
  skeletonizer: ^2.1.2

  # Security packages
  flutter_secure_storage: ^9.0.0
  sqlcipher_flutter_libs: ^0.6.1
  sqflite_sqlcipher: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  floor_generator: ^1.5.0

flutter:

  uses-material-design: true

